In [1]:
import numpy as np 
import pandas as pd

import os
for dirname, _, filenames in os.walk(r"C:\Users\Karishma Salvi\Downloads\Simpliilearn\Mercedezbenz\input"):
    for filename in filenames:
        print(os.path.join(dirname, filename))

C:\Users\Karishma Salvi\Downloads\Simpliilearn\Mercedezbenz\input\test.csv
C:\Users\Karishma Salvi\Downloads\Simpliilearn\Mercedezbenz\input\train.csv

In [2]:
train = pd.read_csv(r"C:\Users\Karishma Salvi\Downloads\Simpliilearn\Mercedezbenz\input\train.csv")
test = pd.read_csv(r"C:\Users\Karishma Salvi\Downloads\Simpliilearn\Mercedezbenz\input\test.csv")

In [3]:
train.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

In [4]:
train = train.drop('ID',axis =1)
test = test.drop('ID',axis =1)

In [5]:
X = train.drop('y',axis=1).copy()
y = train.y

In [6]:
X.head()

,X0,X1,X2,X3,X4,X5,X6,X8,X10,X11,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,k,v,at,a,d,u,j,o,0,0,...,0,0,1,0,0,0,0,0,0,0
1,k,t,av,e,d,y,l,o,0,0,...,1,0,0,0,0,0,0,0,0,0
2,az,w,n,c,d,x,j,x,0,0,...,0,0,0,0,0,0,1,0,0,0
3,az,t,n,f,d,x,l,e,0,0,...,0,0,0,0,0,0,0,0,0,0
4,az,v,n,f,d,h,d,n,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
y.head()

0    130.81
1     88.53
2     76.26
3     80.62
4     78.02
Name: y, dtype: float64

In [9]:
X_Miss = []
for i in X.isnull().sum().items():
    if (i[1] != 0) :
        X_Miss.append(i[0])
print('X_Miss', X_Miss)

test_Miss = []
for i in test.isnull().sum().items():
    if (i[1] !=0):
        test_Miss.append(i[0])
print('test_Miss', test_Miss)

X_Miss []
test_Miss []

In [10]:
X_desc = X.describe(include='O')
X_desc

          X0    X1    X2    X3    X4    X5    X6    X8
count   4209  4209  4209  4209  4209  4209  4209  4209
unique    47    27    44     7     4    29    12    25
top        z    aa    as     c     d     w     g     j
freq     360   833  1659  1942  4205   231  1042   277

In [11]:
test_desc = test.describe(include='O')
test_desc

          X0    X1    X2    X3    X4    X5    X6    X8
count   4209  4209  4209  4209  4209  4209  4209  4209
unique    49    27    45     7     4    32    12    25
top       ak    aa    as     c     d     v     g     e
freq     432   826  1658  1900  4203   246  1073   274

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(X, y, train_size=0.8, test_size=0.2, random_state=0)

In [13]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

# Function for comparing different approaches
def score_dataset(X_train, X_valid, y_train, y_valid):
    model = RandomForestRegressor(n_estimators=100, random_state=0)
    model.fit(X_train, y_train)
    preds = model.predict(X_valid)
    return mean_absolute_error(y_valid, preds)

In [14]:
from sklearn.preprocessing import LabelEncoder
le_X_train = X_train.copy()
le_X_valid = X_valid.copy()
le= LabelEncoder()

for i in X_desc.columns:
    le_X_train[i]=le.fit_transform(le_X_train[i])
for i in X_desc.columns:
    le_X_valid[i]=le.fit_transform(le_X_valid[i])

print("MAE from Approach 1 (Lable Encoding):") 
print(score_dataset(le_X_train, le_X_valid, y_train, y_valid))

MAE from Approach 1 (Lable Encoding):
6.850257963457775

In [15]:
le_X_train.head()

,X0,X1,X2,X3,X4,X5,X6,X8,X10,X11,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
3540,6,13,15,5,3,22,8,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3748,7,23,37,0,3,25,6,4,0,0,...,0,0,1,0,0,0,0,0,0,0
1287,28,0,8,5,3,2,9,20,0,0,...,0,0,0,0,0,0,0,0,0,0
2856,18,19,37,5,3,20,6,6,0,0,...,0,0,0,0,0,0,0,0,0,0
1380,11,13,38,2,3,2,3,13,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
from sklearn.preprocessing import OrdinalEncoder
label_X_train = X_train.copy()
label_X_valid = X_valid.copy()

ordinal_encoder = OrdinalEncoder()
label_X_train[X_desc.columns] = ordinal_encoder.fit_transform(label_X_train[X_desc.columns])
label_X_valid[X_desc.columns] = ordinal_encoder.fit_transform(label_X_valid[X_desc.columns])

print("MAE from Approach 2 (Ordinal Encoding):") 
print(score_dataset(label_X_train, label_X_valid, y_train, y_valid))

MAE from Approach 2 (Ordinal Encoding):
6.850257963457775

In [17]:
lable_test = test.copy()

for i in X_desc.columns:
    lable_test[i]=le.fit_transform(lable_test[i])

In [18]:
label_X_train.head()

,X0,X1,X2,X3,X4,X5,X6,X8,X10,X11,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
3540,6.0,13.0,15.0,5.0,3.0,22.0,8.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,0
3748,7.0,23.0,37.0,0.0,3.0,25.0,6.0,4.0,0,0,...,0,0,1,0,0,0,0,0,0,0
1287,28.0,0.0,8.0,5.0,3.0,2.0,9.0,20.0,0,0,...,0,0,0,0,0,0,0,0,0,0
2856,18.0,19.0,37.0,5.0,3.0,20.0,6.0,6.0,0,0,...,0,0,0,0,0,0,0,0,0,0
1380,11.0,13.0,38.0,2.0,3.0,2.0,3.0,13.0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(le_X_train)
X_valid_scaled = scaler.fit_transform(le_X_valid)
test_scaled = scaler.fit_transform(lable_test)

In [20]:
columns = []
for col in le_X_train.columns:
    columns.append(col)
columns

['X0',
 'X1',
 'X2',
 'X3',
 'X4',
 'X5',
 'X6',
 'X8',
 'X10',
 'X11',
 'X12',
 'X13',
 'X14',
 'X15',
 'X16',
 'X17',
 'X18',
 'X19',
 'X20',
 'X21',
 'X22',
 'X23',
 'X24',
 'X26',
 'X27',
 'X28',
 'X29',
 'X30',
 'X31',
 'X32',
 'X33',
 'X34',
 'X35',
 'X36',
 'X37',
 'X38',
 'X39',
 'X40',
 'X41',
 'X42',
 'X43',
 'X44',
 'X45',
 'X46',
 'X47',
 'X48',
 'X49',
 'X50',
 'X51',
 'X52',
 'X53',
 'X54',
 'X55',
 'X56',
 'X57',
 'X58',
 'X59',
 'X60',
 'X61',
 'X62',
 'X63',
 'X64',
 'X65',
 'X66',
 'X67',
 'X68',
 'X69',
 'X70',
 'X71',
 'X73',
 'X74',
 'X75',
 'X76',
 'X77',
 'X78',
 'X79',
 'X80',
 'X81',
 'X82',
 'X83',
 'X84',
 'X85',
 'X86',
 'X87',
 'X88',
 'X89',
 'X90',
 'X91',
 'X92',
 'X93',
 'X94',
 'X95',
 'X96',
 'X97',
 'X98',
 'X99',
 'X100',
 'X101',
 'X102',
 'X103',
 'X104',
 'X105',
 'X106',
 'X107',
 'X108',
 'X109',
 'X110',
 'X111',
 'X112',
 'X113',
 'X114',
 'X115',
 'X116',
 'X117',
 'X118',
 'X119',
 'X120',
 'X122',
 'X123',
 'X124',
 'X125',
 'X126',
 'X127',
 'X128',
 'X129',
 'X130',
 'X131',
 'X132',
 'X133',
 'X134',
 'X135',
 'X136',
 'X137',
 'X138',
 'X139',
 'X140',
 'X141',
 'X142',
 'X143',
 'X144',
 'X145',
 'X146',
 'X147',
 'X148',
 'X150',
 'X151',
 'X152',
 'X153',
 'X154',
 'X155',
 'X156',
 'X157',
 'X158',
 'X159',
 'X160',
 'X161',
 'X162',
 'X163',
 'X164',
 'X165',
 'X166',
 'X167',
 'X168',
 'X169',
 'X170',
 'X171',
 'X172',
 'X173',
 'X174',
 'X175',
 'X176',
 'X177',
 'X178',
 'X179',
 'X180',
 'X181',
 'X182',
 'X183',
 'X184',
 'X185',
 'X186',
 'X187',
 'X189',
 'X190',
 'X191',
 'X192',
 'X194',
 'X195',
 'X196',
 'X197',
 'X198',
 'X199',
 'X200',
 'X201',
 'X202',
 'X203',
 'X204',
 'X205',
 'X206',
 'X207',
 'X208',
 'X209',
 'X210',
 'X211',
 'X212',
 'X213',
 'X214',
 'X215',
 'X216',
 'X217',
 'X218',
 'X219',
 'X220',
 'X221',
 'X222',
 'X223',
 'X224',
 'X225',
 'X226',
 'X227',
 'X228',
 'X229',
 'X230',
 'X231',
 'X232',
 'X233',
 'X234',
 'X235',
 'X236',
 'X237',
 'X238',
 'X239',
 'X240',
 'X241',
 'X242',
 'X243',
 'X244',
 'X245',
 'X246',
 'X247',
 'X248',
 'X249',
 'X250',
 'X251',
 'X252',
 'X253',
 'X254',
 'X255',
 'X256',
 'X257',
 'X258',
 'X259',
 'X260',
 'X261',
 'X262',
 'X263',
 'X264',
 'X265',
 'X266',
 'X267',
 'X268',
 'X269',
 'X270',
 'X271',
 'X272',
 'X273',
 'X274',
 'X275',
 'X276',
 'X277',
 'X278',
 'X279',
 'X280',
 'X281',
 'X282',
 'X283',
 'X284',
 'X285',
 'X286',
 'X287',
 'X288',
 'X289',
 'X290',
 'X291',
 'X292',
 'X293',
 'X294',
 'X295',
 'X296',
 'X297',
 'X298',
 'X299',
 'X300',
 'X301',
 'X302',
 'X304',
 'X305',
 'X306',
 'X307',
 'X308',
 'X309',
 'X310',
 'X311',
 'X312',
 'X313',
 'X314',
 'X315',
 'X316',
 'X317',
 'X318',
 'X319',
 'X320',
 'X321',
 'X322',
 'X323',
 'X324',
 'X325',
 'X326',
 'X327',
 'X328',
 'X329',
 'X330',
 'X331',
 'X332',
 'X333',
 'X334',
 'X335',
 'X336',
 'X337',
 'X338',
 'X339',
 'X340',
 'X341',
 'X342',
 'X343',
 'X344',
 'X345',
 'X346',
 'X347',
 'X348',
 'X349',
 'X350',
 'X351',
 'X352',
 'X353',
 'X354',
 'X355',
 'X356',
 'X357',
 'X358',
 'X359',
 'X360',
 'X361',
 'X362',
 'X363',
 'X364',
 'X365',
 'X366',
 'X367',
 'X368',
 'X369',
 'X370',
 'X371',
 'X372',
 'X373',
 'X374',
 'X375',
 'X376',
 'X377',
 'X378',
 'X379',
 'X380',
 'X382',
 'X383',
 'X384',
 'X385']

In [21]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns = columns)
X_valid_scaled = pd.DataFrame(X_valid_scaled, columns = columns)
test_scaled = pd.DataFrame(test_scaled, columns = columns)

In [23]:
from sklearn.decomposition import PCA
from xgboost import XGBRegressor
from sklearn.metrics import accuracy_score

In [24]:
pca =PCA(n_components=0.97, random_state=102)
Xtrain_trans=pca.fit_transform(X_train_scaled)
XValid_trans=pca.transform(X_valid_scaled)
test_trans=pca.transform(test_scaled)
print(X_train_scaled.shape)
print(Xtrain_trans.shape)
print(X_valid_scaled.shape)
print(XValid_trans.shape)
print(test_scaled.shape)
print(test_trans.shape)

(3367, 376)
(3367, 94)
(842, 376)
(842, 94)
(4209, 376)
(4209, 94)

In [25]:
xgb=XGBRegressor(n_estimators=1000, learning_rate=0.05, n_jobs=4)

In [26]:
xgb1=XGBRegressor(n_estimators=500, learning_rate=0.05, n_jobs=4)

In [27]:
xgb1=XGBRegressor(n_estimators=500, learning_rate=0.05, n_jobs=4)

In [28]:
xgb.fit(Xtrain_trans, y_train, early_stopping_rounds=5, eval_set=[(XValid_trans, y_valid)], verbose=False)

C:\Users\Karishma Salvi\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\sklearn.py:835: UserWarning: `early_stopping_rounds` in `fit` method is deprecated for better compatibility with scikit-learn, use `early_stopping_rounds` in constructor or`set_params` instead.
  warnings.warn(

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.05, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=1000, n_jobs=4, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [29]:
ypred=xgb.predict(XValid_trans)

In [30]:
print(xgb.score(Xtrain_trans,y_train))
print(xgb.score(XValid_trans,y_valid))

0.7706894364848388
0.4233031135157479

In [31]:
output = pd.DataFrame(xgb.predict(test_trans))

In [32]:
Output = output.to_csv(r"C:\Users\Karishma Salvi\Downloads\Simpliilearn\Mercedezbenz\input\Output.csv")